### ISSUE TITLE
Help on running RMBT servers

### ISSUE THREAD

**Issue by hoang-tranviet** [rtr-nettest/open-rmbt#1]
Hello everyone,

Thank you for building and open-sourcing the program.
For research purpose, I want to add some tests to the RMBT. I am trying to run the control server and the accompanies, but have faced some issues. Would you mind to help to explain some points, I am sorry if these are naive questions:
- In step 2 of DB server, I don't get where the rmbt_init.sql and rmbt.sql files come from.
- Is the RMBT_SECRETKEY mandatory and how could I create it?

Thank you in advance,

Hoang

**Comment by cproof** [comment]
Dear Hoang,

we are aware of the problem and are currently working on updating and open-sourcing the `rmbt_init.sql` and `rmbt.sql` files. Expect them to be up very soon.

The `RMBT_SECRETKEY` is mandatory, you can create your own key with the makefile and instructions supplied in the [rtr-nettest/rmbt-server](https://github.com/rtr-nettest/rmbt-server) repository.

If you only want to IAS speed, you can also skip setting up a ControlServer and directly work with the [rtr-nettest/rmbt-server](https://github.com/rtr-nettest/rmbt-server) (unsetting `CHECK_TOKEN` in the config) and the commandline `RMBTClient` supplied in this repository as well.

**Comment by hoang-tranviet** [comment]
Hello @cproof,

Thanks for the brisk response,
It is very good that I can temporarily skip the ControlServer and work directly with the client for the new feature in the meantime.
My concern is, will the iOS app be able to work directly with the RMBT-Server in the same fashion?

Thank you.

**Comment by cproof** [comment]
Dear @hoang-tranviet, 
I just committed the [rmbt.sql](https://github.com/rtr-nettest/open-rmbt/blob/master/install/postgresql/rmbt.sql) and [rmbt_init.sql](https://github.com/rtr-nettest/open-rmbt/blob/master/install/postgresql/rmbt_init.sql) files. With these, it should be possible to run your own ControlServer.

If you want to do further research, there are also [multiple forks](https://www.rtr.at/en/tk/netztestfaq_allgemein_0200) of our project in the wild, some of which contain further modifications and examples on how to build and run an open-rmbt instance, e.g. [NetMetr by CZ.NIC](https://gitlab.labs.nic.cz/labs/netmetr/tree/master/RMBTControlServer)

**Comment by cproof** [comment]
Dear @hoang-tranviet 
did you manage to set up the system? If so, please close this ticket.
