### ISSUE TITLE
cat rmbt_init.sql | psql rmbt -1 error

### ISSUE THREAD

**Issue by alexandersokol** [rtr-nettest/open-rmbt#11]
Hello!

I'm getting an error while running

`cat rmbt_init.sql | psql rmbt -1`

```
ERROR:  syntax error at or near "SELECT"
LINE 7: SELECT pg_catalog.setval('public.test_server_uid_seq', 86, t...
```

this is the last line in the rmbt_init.sql file.

how I can fix it?

**Comment by djagar** [comment]
Hello,
the latest commit should have fixe the error.

**Comment by alexandersokol** [comment]
Thank you.
Now it works correctly
