### ISSUE TITLE
web.xml issue

### ISSUE THREAD

**Issue by HerzogVolpe** [rtr-nettest/open-rmbt#18]
Wachutka Martin asked me if i could mace a little Testing-Device fort the FiberServiece and the Breitbandbüro, soI tried to compile the CLI-Client myself by cloning the repository, but everything has to be compilable in order for the client to compile.
So I fixed a lot of dependency issues on my system, but now im stuck on an error within the web.xml file.
For the 2 rows it tells me that
"The listener-class element declares a class in the application must be registered as a web application listener bean. The 
 value is the fully qualified classname of the listener class."
and
"cvc-complex-type.2.4.d: Invalid content was found starting with element 'listener-class'. No child element is expected at this point." 

[web.txt](https://github.com/rtr-nettest/open-rmbt/files/6220544/web.txt)

Im pretty new to this whole Java-Eclipse Stuff and i would be glad for some help.
![grafik](https://user-images.githubusercontent.com/56998323/112813456-7fd6e180-907e-11eb-9841-343ca399ac63.png)

**Comment by cproof** [comment]
Thank you for raising the issue! The `web.xml` was working but not compliant with the xsd.
It should now be fixed.
