### ISSUE TITLE
problem with provided rmbt_init.sql

### ISSUE THREAD

**Issue by dabeani** [rtr-nettest/open-rmbt#2]
Hi,

Thank you for your support and provide us the needed SQL files.
But now, i get in some troubles with import the rmbt_init.sql file. Below you will se the error messages.

![image](https://user-images.githubusercontent.com/7305629/37223255-3d4b5418-23d0-11e8-90fc-28afe2f1b4b8.png)

Any suggestions about that syntax error?

br
Bernhard

**Comment by cproof** [comment]
Hi,

did you start with importing `rmbt.sql` before `rmbt_init.sql`?
`rmbt.sql` contains the empty tables and data structures, while `rmbt_init.sql` contains an initial set of values.

**Comment by hoang-tranviet** [comment]
Hi @cproof,

Thank you for sharing the .sql file.
I tried importing rmbt.sql but got the errors as below.

`cat rmbt.sql | psql rmbt -1 -a
`
```
--
-- Name: clc12_all_oesterreich_gid_seq; Type: SEQUENCE; Schema: public; Owner: rmbt
--
CREATE SEQUENCE clc12_all_oesterreich_gid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ERROR:  syntax error at or near "AS"
LINE 2:     AS integer
            ^
ALTER TABLE clc12_all_oesterreich_gid_seq OWNER TO rmbt;
ERROR:  current transaction is aborted, commands ignored until end of transaction block
--
-- Name: clc12_all_oesterreich_gid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: rmbt
--
ALTER SEQUENCE clc12_all_oesterreich_gid_seq OWNED BY clc12_all_oesterreich.gid;
ERROR:  current transaction is aborted, commands ignored until end of transaction block

```

This is new to me, maybe I missed something.

Hoang

**Comment by cproof** [comment]
Which version of PostgreSQL are you using?

`CREATE SEQUENCE ... AS ...` is supported in PostgreSQL versions >=10

**Comment by hoang-tranviet** [comment]
Well, I was using PostgreSQL 9.6 on Fedora.
Now I am removing it and installing PostgresSQL 10.3.

Thank you for the suggestion.

**Comment by dabeani** [comment]
same here - after upgrading the database the errors are gone.

**Comment by cproof** [comment]
Thank you for the feedback, I'll update the README accordingly.
While the database itself does not require any PostgreSQL 10-specific functionality, it seems that the `pg_dump` utility distributed with PostgreSQL 10 creates SQL that only can be re-imported by PostgreSQL 10.
