### ISSUE TITLE
Guide improvement.

### ISSUE THREAD

**Issue by GreatDandashi** [rtr-nettest/open-rmbt#20]
Is there a possibility to give better and more thorough instructions on how to build and run a fully working version?
The given instructions are incomplete and very vague.
Thank you.

**Comment by GreatDandashi** [comment]
I have no idea how this actually connects to the Open-Rmbt-Website repository.

**Comment by dzlabing** [comment]
Thank you for your feedback.
We are happy to provide Open Source, but we do not have resources to give individual support.
