### ISSUE TITLE
test-server does not accept client token

### ISSUE THREAD

**Issue by ruhollahShafiee** [rtr-nettest/open-rmbt#4]
When the client receive token from control-server and then send to test-server the test-server does not  accept the token . 
I add secret.key's content  as value of  `RMBT_SECRETKEY` parmameter in tomcat8 and run test-server by this command: `./rmbtd -c "server.crt" -k "server.key" -l 443 -w`. 
the control-server generate a token successfully but the test-server doesn't accept this token.
Can you help me about this?

**Comment by cproof** [comment]
Did you add the secret key in the `key` column of the `test_server` database table?
Do you get an error message in syslog on your test-server instance?
