### ISSUE TITLE
Initialization scripts collide with each other.

### ISSUE THREAD

**Issue by cifffi** [rtr-nettest/open-rmbt#5]
Hello,
I'm trying to set up my own RMBT servers simply by following instructions provided in readme.MD. In order to set up DB server I have to run two initialization scripts (rmbt.sql & rmbt_init.sql), but they collide with each other (ie. both of them are creating same objects or in rmbt.sql some constrains are created which are violated when rmbt_init.sql tries to insert data). Therefore I'm not able to execute second script. 
Any suggestions what should I do? Could you try to dump your DB again? I would like to avoid changing scripts manually. 

BR, Filip

**Comment by cproof** [comment]
Hello Filip,
can you please copy the error log you get from PostgreSQL?
And in any case, we'll provide fresh dumps for DB and structures.
BR, Thomas

**Comment by cifffi** [comment]
I've got multiple errors like (same goes for every table, sequence, index):
- ERROR:  relation "as2provider" already exists
- ERROR:  relation "as2provider_uid_seq" already exists

Solved it by adding IF NOT EXISTS after every CREATE TABLE/SEQUENCE/INDEX

Then I've got:
- ERROR:  insert or update on table "as2provider" violates foreign key constraint "as2provider_provider_id_fkey"
- DETAIL:  Key (provider_id)=(1) is not present in table "provider".

Solved it by temporarily disabling constraints

Right now I'm stuck on:
- ERROR:  multiple primary keys for table "as2provider" are not allowed


BR, Filip

**Comment by cifffi** [comment]
I din't want to close the issue, therefore reopening again.

**Comment by cproof** [comment]
I just updated the SQL dumps, can you please try again?

**Comment by cifffi** [comment]
I dropped DB and recreated it again before running scripts. Error with foreign keys still remain.

- ERROR: insert or update on table "as2provider" violates foreign key constraint "as2provider_provider_id_fkey"
- DETAIL: Key (provider_id)=(1) is not present in table "provider".

Foreign keys needs to be disabled or data needs to be inserted in right order (if possible)

**Comment by cproof** [comment]
I updated the `rmbt_init.sql` accordingly and tested it using a empty database. The import should now work.

**Comment by cifffi** [comment]
Working perfectly. Thanks
