### ISSUE TITLE
Connect ControlServer with Android App

### ISSUE THREAD

**Issue by Oremuss** [rtr-nettest/open-rmbt#7]
[Question] Hello open-rmbt masters and enthusiasts :) 

I want to measure 4G and QoS via open-rmbt android app and store data to my database but I am  not that much experienced in this area  so I have some questions about how to get Android App working together with server running on my laptop - if it is even possible :). 
******************************************************************************************************
I did follow README.MD guide  step by step. 
Databse server:  I have created everything, added secret key to the table, everything seems to be working here.
******************************************************************************************************

Control-, Map- and StatisticServer - this is something I am a little confused about. I installed every dependency and stuff and changed   `/etc/tomcat8/context.xml`.  I have copied those two Contexts from README.MD and substitued parts with []. Then I built servers and restarted service tomcat8. But after trying to reach server via browser it didnt work. Then I tried delete one of those contexts and in `/etc/tomcat8/context.xml` is context only for ControlServer. Now when I test it via web browser for example with version of server it returns  `{"version":"master_822cccf-dirty"}`. Well I guess it works  as it suppose to work. 

 Now I am confused where should be located that other context for statistic/map server??
********************************************************************************************************
I have made my ControlServer public via tunnel and it can be reached from internet, so I have tried to put address to the Android App but app after build and run says it cannot find host. 

`cp /var/lib/tomcat7/webapps/RMBTControlServer/WEB-INF/lib/postgresql-XXX.jdbcYY.jar /var/lib/postgresql/netztest/RMBTSharedCode/lib/postgresql-XXX.jdbcYY.jar`

I have tried to copy the following .jar but I dont have the folder "netztest" in` /var/lib/postgresql/ `I only have there my versoin of my postgres -> `/var/libpostgresql/10/` and so on but there is no folder `RMBTSharedCode/lib` , so should I make that folder or copy it from source code or it should have been there somehow created by commands I didnt use??
******************************************************************************************************
Thank you in advance for reply and like I said I am noe much experienced. If I am doing somwthing wrong can you point me to right direction ? I would really appreciate some detailed instruction how to make it but I guess every programmer is so too busy to make something like that :D I will be happy even if you tell me what am I doing wrong :) Best regards.

**Comment by cproof** [comment]
Hello @Oremuss 
thank you for your interest 👍 

Regarding the postgres jar: You can find instructions here: https://jdbc.postgresql.org/documentation/head/tomcat.html - normally, the operating system will take care of this.

The path to the servers can be configured with tomcat, in the standard configuration they are usually reachable under
`http://localhost:8080/RMBTControlServer/version`
`http://localhost:8080/RMBTMapServer/version`
`http://localhost:8080/RMBTStatisticServer/version`

For Android, you need to enter the hostname of your ControlServer hiere: https://github.com/rtr-nettest/open-rmbt/blob/master/RMBTAndroid/res/values/defaults.xml i.e. set `default_control_host` to `yourhost.domain.com`.

You're right, the documentation is lacking at some places. If you have suggestions on what to add / where we're unclear, please consider sharing your experience in this ticket or a PR ;-)

**Comment by Oremuss** [comment]
Thank you for reply 👍  

After I successfully run it ( I hope so ) I will write down everything what was unclear . I understand that for someone who is in this project quiet some time all these things are automatically done, but for me as a "noob", some things are not clear immediately. 

Anyway,  when I reach `http://localhost:8080/RMBTControlServer/version` it will return  
> {"version":"master_822cccf-dirty"}
vut when I try reach  `http://localhost:8080/RMBTMapServer/version` or `http://localhost:8080/RMBTStatisticServer/version`  I get response : "_Internal Server error. The server encountered an unexpected condition which prevented it from fulfilling the request._" 

Now this is when in `/etc/tomcat8/context.xml` is **ONLY**  this code : 
`<Context>`
`<Resource`
   name="jdbc/rmbt"
   auth="Container"  
   type="javax.sql.DataSource"  
   maxActive="200" maxIdle="10" maxWait="10000"
   url="jdbc:postgresql://localhost:5432/rmbt"
   driverClassName="org.postgresql.Driver"
   username="rmbt_control" password="pass"
   description="DB RW Connection" />
`<Parameter name="RMBT_SECRETKEY" value="secretkey" override="false" />`
`</Context>`
*****************************************************************************************************
But when I add the second context to the /etc/tomcat8/context.xml  as is written in README.MD everything will return `HTTP STATUS 404 - Not found `, even the RMBTControlServer. 

`<Context>`
`<Resource` 
   `name="jdbc/rmbtro" `
   `auth="Container"`
 `  type="javax.sql.DataSource"`
   `maxActive="200" maxIdle="10" maxWait="10000"`
  ` url="jdbc:postgresql://localhost:5432/rmbt"`
   `driverClassName="org.postgresql.Driver"`
   `username="rmbt" password="pass"`
   `description="DB RO Connection" />`
`</Context>`

**Any idea what might be wrong?**

**Comment by Oremuss** [comment]
OK here is little update, according to tomcat8 documentation  :

> _files that define Context elements may only define a single Context element._

So I can have only one context element in one file. I have tried that according documentation:
>Individual Context elements may be explicitly  defined:
> - In an individual file at /META-INF/context.xml inside the application files
> - In individual files (with a ".xml" extension) in the $CATALINA_BASE/conf/[enginename]/[hostname]/

So I have tried both solution and none of them works :(  I put to $CATALINA_BASE/conf/Catalina/localhost three files named RMBTControlServer.xml, RMBTMapServer.xml and RMBTStatisticServer.xml but still with no success. 
*******************************************************************************************
Its only context.xml in  `/etc/tomcat8/context.xml` that works, end if there is the second context alone, Map and Statistic servers are working, but no Control and if there is first context than only Control works. SO I have no idea how to run all of them.

**Comment by cproof** [comment]
> But when I add the second context to the /etc/tomcat8/context.xml

In the `context.xml`, you only define a single context.
If you want to run both servers on the same tomcat instance, this context would be:

```xml
<Context>
<Resource 
   name="jdbc/rmbt" 
   auth="Container"
   type="javax.sql.DataSource"
   maxActive="200" maxIdle="10" maxWait="10000"
   url="jdbc:postgresql://[db host]/rmbt"
   driverClassName="org.postgresql.Driver"
   username="rmbt_control" password="[db r/w pass]"
   description="DB RW Connection" />
<Parameter name="RMBT_SECRETKEY" value="[rmbt qos secret key]" override="false" />
<Resource 
   name="jdbc/rmbtro" 
   auth="Container"
   type="javax.sql.DataSource"
   maxActive="200" maxIdle="10" maxWait="10000"
   url="jdbc:postgresql://[db host]/rmbt"
   driverClassName="org.postgresql.Driver"
   username="rmbt" password="[read only pass]"
   description="DB RO Connection" />
</Context>
```

Sorry if this is unclear from the `README`.

**Comment by Oremuss** [comment]
Ok I it works 🥇 I have to admit that I have already tried this solution once, but I guess somehow it didtn work, but now it is working, thx :)
